# Commmand to compile tex -> pdf
$pdf_mode = 1;
#
# Use biber instead of bibtex
$bib_program = 'biber';
# Setup the main latex file that includes all other parts as separate tex file
@default_files = ('main.tex');
#
# Specify the output folder
$out_dir = 'build';
#
# Add some pdflatex parameters
$pdflatex = 'pdflatex -extra-mem-top=20000000';
# Maybe some additional useful parameter
#  --shell-escape --enable-write18
# Bibtex control option
$bibtex_use = 2;
# turn off the recorder
$recorder = 0;
#
# Setup cleaning for 'latexmk -c' respectively 'latexmk -C' command
#
# Cleanup before build the document
@generated_exts = (@generated_exts, 'synctex.gz');
# Add some additional filetypes
$clean_ext = 'fls synctex.gz mw auxlock %R.%R.gnuplot %R*.synctex.gz';
